version: '3.9'
services:
  reveal-md:
    image: webpronl/reveal-md
    ports:
    - 8099:1948
    # To create the directory where the site will be generated...
    #   mkdir assets
    #   chmod 777 assets
    command: ["/slides", "README.md", "--css", "sample.css", "--static", "/assets"]
    volumes:
    - ".:/slides"
    - "./assets:/assets"