version: 0.2

phases:
  pre_build:
    commands:
      - echo s3://${S3CFBUCKET}/api 
      - aws s3 ls s3://${S3CFBUCKET}/

  build:
    commands:
      - cd coll-health-obj-analysis
      - docker-compose -f sample/docker-compose-static.yml up --build
      - aws s3 cp --recursive sample/present_schema s3://${S3CFBUCKET}/present_schema
