Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line


AllCops:
  NewCops: enable
  SuggestExtensions: false
