# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-lambda'
gem 'aws-sdk-ssm'
gem 'base64'
gem 'json'
gem 'nokogiri'
gem 'uc3-ssm', git: 'https://github.com/CDLUC3/uc3-ssm.git', tag: '1.0.6'

gem 'rubocop'
