Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false  
Metrics/CyclomaticComplexity:
  Enabled: false  

# temp ignore
Style/Documentation:
  Enabled: false


AllCops:
  NewCops: enable

