# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-lambda'
gem 'aws-sdk-ssm'
gem 'base64'
gem 'erb'
gem 'json'
gem 'json-schema'
gem 'mustache'
gem 'mysql2'
gem 'nokogiri'
gem 'opensearch-ruby'
gem 'uc3-ssm', git: 'https://github.com/CDLUC3/uc3-ssm.git', tag: '1.0.4'

gem 'colorize'
gem 'logger'
gem 'rspec'
gem 'rubocop'

# apt-get install libyaml-dev is required ... only on dev box currently
# gem 'irb'
# gem 'debug'
