source 'https://rubygems.org'

gem 'json'
gem 'aws-sdk-lambda'
gem 'uc3-ssm', '0.3.10', git: 'https://github.com/CDLUC3/uc3-ssm.git', branch: 'main'
gem 'base64'
gem 'nokogiri'
gem 'mysql2'
gem 'opensearch-ruby'
