default:
  default-params: 
    QUERY: collection
    MNEMONIC: merritt_demo
    LIMIT: 10
  opensearch:
    host: 'https://localhost:9200'
    user: 'admin'
    password: 'admin'
    transport_options:
      ssl: 
        verify: false
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: "{!SSM: billing/db-host}"
    database: "{!SSM: billing/db-name}"
    port: 3306
    username: "{!SSM: billing/readwrite/db-user}"
    password: "{!SSM: billing/readwrite/db-password}"
  config-dateime:
    build: '2023-10-13 16:00:00'
    analysis: '2023-10-13 16:00:00'
    test: '2023-10-13 16:00:00'
  debug:
    export_max: 5
    print_max: 1
  batch:
    process-max: 50
  gather-ids:
    select: |
      select o.id
      from inv.inv_objects o
      inner join inv.inv_collections_inv_objects icio on icio.inv_object_id = o.id
      inner join inv.inv_collections c on c.id = icio.inv_collection_id
      where 1=1
      and c.mnemonic not in ('cdl_dryad', 'ucb_open_context', 'cdl_uc3_etdreports') 
      and c.mnemonic not like '%_dash'
      and c.mnemonic not like 'mrt_%'
    default-exclusion: |
      and 0 = 1
      limit {{LIMIT}}
    build-exclusion: |
      and not exists (
        select 1 from object_health_json h where h.inv_object_id = o.id and h.build_updated > o.modified
      )
      order by o.modified desc
      limit {{LIMIT}}
    analysis-exclusion: |
      and exists(
        select 1 from object_health_json h where h.inv_object_id = o.id and h.build is not null
      )
      and not exists (
        select 1 from object_health_json h where h.inv_object_id = o.id and h.analysis_updated >= h.build_updated
      )
      order by o.modified desc
      limit {{LIMIT}}
    tests-exclusion: |
      and exists(
        select 1 from object_health_json h where h.inv_object_id = o.id and h.analysis is not null
      )
      and not exists (
        select 1 from object_health_json h where h.inv_object_id = o.id and h.tests_updated >= h.analysis_updated
      )
      order by o.modified desc
      limit {{LIMIT}}
    # prioritized set of queries to use to find work to be performed.  If one query returns no results, the next one will be run
    queries:
      collection: |
        and c.mnemonic = '{{MNEMONIC}}'
      has-build: |
        and exists (select 1 from object_health_json h where h.inv_object_id = o.id)
  collection_taxonomy:
    colltax_skip:
      patterns: 
      - ^.*_dash$
      - ^mrt_.*$
      mnemonics:
      - ucb_open_context
      - cdl_dryad
      - cdl_uc3_etdreports
      #rhodecode
    colltax_lsta:
      patterns:
      - ^lsta_.*$
    colltax_nuxeo:
      #mnemonics: 
      #- ...
    # tind
    # expanded bags (UCI, UCSC)
    # etds
    colltax_cdl:
      mnemonics:
      - merritt_demo
      - escholarship
  analysis-inputs:
    duplicate-checksum:
      note: consider excluding opencontext
      query: |
        select source, digest_value, full_size, count(*) 
        from inv_files 
        where source='producer' and full_size=billable_size 
        group by source, digest_value, full_size 
        having count(*) > 1 order by count(*);
    average-object-size-for-collection:
      description: compute average, mean file size to identify outliers
    average-file-size-for-collection-and-mime:
      description: compute average, mean file size to identify outliers
    average-file-size-for-mime-type:
      description: compute average, mean file size to identify outliers
    duplicate-title-in-collection:
  analysis-json:
    mime:
      class: MimeTask
      PASS: &sustainable_mimes_pass
        text/plain: ["txt"]
        application/xml: ["xml"]
        image/jpeg: ["jpg", "jpeg"]
        image/tiff: ["tif", "tiff"]
        application/xhtml+xml: ["xhtml"]
        application/pdf: ["pdf"]
        application/atom+xml: ["xml"]
        image/gif: ["gif"]
        text/csv: ["csv"]
        application/x-gzip: ["gzip", "gz"]
        text/html: ["html", "htm"]
        image/png: ["png"]
        application/vnd.openxmlformats-officedocument.wordprocessingml.document: ["docx"]
        application/zip: ["zip"]
        application/msword: ["doc"]
        audio/x-wav: ["wav"]
        audio/mpeg: ["mpeg"]
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: ["xlsx"]
        application/json: ["json"]
        application/mxf: ["mxf"]
        application/gzip: ["gzip", "gz"]
        application/vnd.ms-excel: ["xls"]
        video/mp4: ["mp4"]
        video/quicktime: []
        application/vnd.openxmlformats-officedocument.presentationml.presentation: ["pptx"]
        application/vnd.ms-powerpoint: ["ppt"]
      SKIP: &sustainable_mimes_skip
        plain/turtle: []
        application/rdf+xml: []
      FAIL:
      # x-pkcs: Public-Key Cryptography Standards files provide for certificate storage
        application/x-pkcs12: []
        application/x-pkcs7-certificates: []
      # binary.macroenabled.12: Binary Excel spreadsheet with macros enabled
        application/vnd.ms-excel.sheet.binary.macroenabled.12: []
      # appledouble: Apple dual-forked file typically excluded from containers
        multipart/appledouble: []
      WARN: &sustainable_mimes_warn
        application/octet-stream: []
        application/vnd.chipnuts.karaoke-mmd: []
        application/vnd.ms-excel.sheet.macroenabled.12: []
        application/vnd.ms-powerpoint.presentation.macroenabled.12: []
        application/vnd.ms-word.document.macroenabled.12: []
        application/x-stata-dta: []
        application/x-stata-dta; version=13: []
        application/x-stata-dta; version=14: []
        text/x-stsrc: []
      INFO: &sustainable_mimes_info
        application/x-hdf: []
        application/x-matlab-data: []
        text/x-rsrc: []
        application/x-gtar: []
        application/rtf: []
        audio/x-aiff: []
        application/postscript: []
        text/x-actionscript: []
        image/vnd.adobe.photoshop: []
        audio/vnd.wave: []
        application/x-tika-msoffice: []
        application/x-rar-compressed: []
        application/x-netcdf: []
        video/x-msvideo: []
        model/vnd.mts: []
        text/tab-separated-values: ["tsv"]
        image/x-raw-panasonic: []
        text/x-matlab: []
        application/x-dbf: []
        application/x-7z-compressed: []
        application/x-shapefile: []
        text/x-vcard: []
        video/x-matroska: []
        application/x-tar: []
        image/svg+xml: []
        image/x-raw-canon: []
        video/mpeg: []
        application/xv+xml: []
        video/x-ms-wmv: []
        audio/x-ms-wma: []
        application/x-shockwave-flash: []
        text/x-python: []
        video/x-m4v: []
        application/x-sh: []
        application/x-dosexec: []
        application/java-vm: []
        image/x-ms-bmp: []
        text/x-objcsrc: []
        application/x-webarchive: []
        application/x-bzip2: []
        message/rfc822: []
        application/vnd.ms-pki.stl: []
        text/x-ruby: []
        application/x-tika-ooxml: []
        text/x-log: []
        text/x-perl: []
        application/marc: []
        text/x-web-markdown: ["md"]
        application/dicom: []
        application/vnd.oasis.opendocument.spreadsheet: []
        application/x-adobe-indesign: []
        video/x-flv: []
        audio/mp4: []
        application/vnd.quark.quarkxpress: []
        application/vnd.syncml.dm+wbxml: []
        text/x-php: []
        application/vnd.ms-excel.sheet.4: []
        application/x-sqlite3: []
        application/x-iso9660-image: []
        image/bmp: []
        application/javascript: []
        application/vnd.oasis.opendocument.text: []
        text/x-csrc: []
        application/vnd.ms-outlook: []
        text/x-c++src: []
        application/vnd.google-earth.kmz: []
        text/css: []
        application/x-elc: []
        application/x-tex: []
        text/troff: []
        text/x-java-source: []
        application/x-font-ttf: []
        application/java-archive: []
        application/x-font-otf: []
        image/x-pict: []
        application/x-123: []
        image/vnd.radiance: []
        chemical/x-cif: []
        application/vnd.ms-works: []
        application/mathematica: []
        application/vnd.wordperfect: []
        application/x-sas: []
        application/x-bplist: []
        application/zlib: []
        application/x-xz: []
        video/3gpp: []
        application/illustrator: []
        text/x-fortran: []
        audio/vorbis: []
        application/vnd.wordperfect; version=6.x: []
        application/vnd.google-earth.kml+xml: []
        audio/basic: []
        text/x-chdr: []
        application/x-msdownload; format=pe32: []
        application/x-font-bdf: []
        application/vnd.apple.pages: []
        application/vnd.oasis.opendocument.base: []
        video/x-ms-asf: []
        text/x-sql: []
        application/x-stuffit: []
        application/vnd.apple.numbers: []
        application/vnd.rn-realmedia: []
        application/x-msaccess: []
        application/rss+xml: []
        text/sgml: []
        application/x-erdas-hfa: []
        text/x-coldfusion: []
        application/vnd.adobe.xfl: []
        image/x-portable-bitmap: []
        application/x-sas-audit: []
        text/x-pascal: []
        application/x-bzip: []
        application/vnd.iccprofile: []
        application/x-bat: []
        text/x-rst: []
        image/vnd.dxf; format=ascii: []
        application/x-sas-data: []
        application/epub+zip: []
        image/vnd.zbrush.pcx: []
        text/x-d: []
        image/x-portable-graymap: []
        application/vnd.mcd: []
        image/x-xcf: []
        audio/midi: []
        application/x-mspublisher: []
        image/vnd.microsoft.icon: []
        application/x-bibtex-text-file: []
        application/x-compress: []
        application/x-mobipocket-ebook: []
        application/vnd.visio: []
        application/vnd.ms-xpsdocument: []
        application/smil+xml: []
        text/x-prolog: []
        application/vnd.ms-spreadsheetml: []
        message/news: []
        application/vnd.apple.keynote: []
        application/vnd.adobe.air-application-installer-package+zip: []
        text/x-ml: []
        application/vnd.adobe.indesign-idml-package: []
        application/x-sharedlib: []
        application/fits: []
        text/vnd.graphviz: []
        text/x-asciidoc: []
        application/sereal; version=3: []
        text/x-assembly: []
        text/x-basic: []
        text/x-yaml: []
        application/msword2: []
        application/vnd.ms-tnef: []
        image/x-portable-pixmap: []
        application/vnd.ms-word2006ml: []
        text/x-vbasic: []
        application/x-ms-owner: []
        text/x-ini: []
        application/vnd.yamaha.smaf-phrase: []
        application/vnd.ms-excel.sheet.3: []
        image/x-icon: []
        text/x-diff: []
        application/vnd.lotus-freelance: []
        application/x-dtbresource+xml: []
        application/x-msdownload: []
        application/x-msdownload; format=pe64: []
        text/x-tcl: []
        message/x-emlx: []
        application/msword5: []
        text/x-common-lisp: []
        text/x-aspectj: []
        application/vnd.oasis.opendocument.chart: []
        application/x-executable: []
        application/vnd.oasis.opendocument.presentation: []
        text/x-modula: []
        image/wmf: []
        text/calendar: []
        application/vnd.openxmlformats-officedocument.presentationml.template: []
        application/x-xfig: []
        chemical/x-cdx: []
        application/vnd.openxmlformats-officedocument.spreadsheetml.template: []
        text/prs.lines.tag: []
        application/pgp-signature: []
        text/x-groovy: []
        application/vnd.tcpdump.pcap: []
        text/x-haml: []
        application/vnd.mif: []
        application/x-emf: []
        application/vnd.ms-cab-compressed: []
        image/vnd.dwg: []
        application/vnd.adobe.fxp: []
        application/x-font-linux-psf: []
        application/mbox: []
        text/x-c++hdr: []
    # write analysis->classify->content->[type]->[fileid]
    # write analysis->classify->metadata->[type]->[fileid]
    # write analysis->classify->other->[type]->[fileid]
    classify:
      class: ClassifyTask
      # There categorizations are applied in ranked order allowing the re-use of blocks of mime types
      metadata_types:
        common_metadata:
        nuxeo_style_metadata:
        bag_metadata:
        etd_metadata:
        metadata:
      categorize:
      - name: common_metadata
        paths:
        - mets.xml
        - mets.txt
        - mrt-dc.xml
        - cdlmeta.tar.gz
      - name: etd_metadata
        patterns:
        - ^.*_(ucr|ucla)_.*_DATA.xml$
      - name: nuxeo_style_metadata
        templates:
        - "{{LOCALID}}.xml"
      - name: bag_metadata
        paths:
        - bag-info.txt
      - name: metadata
        mimes:
          application/xml:
          application/json:
      - name: secondary
        mimes:
          text/plain:
          application/xhtml+xml:
          application/atom+xml:
          text/html:
        paths:
        - mrt-erc.txt
      - name: complex
        mimes:
          application/x-gzip:
          application/zip:
          application/gzip:
      - name: derivatives
        mimes:
          video/mp4:
          audio/mpeg3:
          image/jpeg:
      - name: content
        mimes:
          <<: *sustainable_mimes_pass
          <<: *sustainable_mimes_info
      # everything else is classified as :na
  analysis-bitstream:
    format-id:
    virus-scan:
    pii-scan:
    accessibility-scan:
  tests:
    sustainable-mime:
      class: MimeTest
      name: Mime type sustainability
      description: Compare file extention (or known mime type) to a list of sustainable mime types.
    mime-extension-mismatch:
      class: MimeExtTest
    object-classification:
      class: ObjectClassificationTest
      categorize:
        PASS:
          multi_digital_files:
          multi_digital_files_with_derivatives:
          digital_file_with_derivatives:
          single_digital_file:
        INFO:
          complex_object:
        WARN:
          derviatives_only:
        FAIL:
          no_content:
    metadata-classification:
      class: MetadataClassificationTest
      categorize:
        PASS:
          metadata_with_secondary:
          single_metadata_file:
        INFO:
          multi_metadata:
        WARN:
          secondary_only:
        FAIL:
          no_metadata:
    ext-url-like-pathname:
      class: ExtUrlTest
    ext-not-present:
      class: ExtNotPresentTest
    empty-file:
      name: Empty file detection
      description: Check file size - WARN if empty producer, INFO if empty system
      class: EmptyTest
    has-delete:
      description: INFO if delete detected
      class: DeletedTest
    doesnt-have-meaningful-erc-what:
      name: Object has meaningful ERC metadata
      description: at first look for empty fields
      class: ErcWhatTest
      categorize:
        FAIL:
        - ^$
        WARN:
        - ^\(:unas\)$
        INFO:
        - ^\(title unknown\)$
        - ^\[Untitled\]$
        - ^Untitled$
    doesnt-have-meaningful-erc-who:
      name: Object has meaningful ERC metadata
      description: at first look for empty fields
      class: ErcWhoTest
      categorize:
        FAIL:
        - ^$
        WARN:
        - ^\(:unav\)$
        - ^\(:unas\)$
    doesnt-have-meaningful-erc-when:
      name: Object has meaningful ERC metadata
      description: at first look for empty fields
      class: ErcWhenTest
      categorize:
        FAIL:
        - ^$
        WARN:
        - ^\(:unas\)$
        - ^\(:unav\)$
        INFO:
        - ^\[Date not indicated\]$
        - ^n\.d\.$
        - ^undated$
    has-embargo:
      name: "Has embargo / had embargo"
      class: EmbargoTest
    no-local-id:
      name: Object has local id
      class: LocalIdTest
      # all tasks and tests can be scoped to run/not run for specific collections
      collection_scope:
        skip:
        #- merritt_demo
        #- escholarship
        - colltax_cdl
        - lsta_pomonapl
        # apply:
        # - mnemonic
    #later
    has-duplicate-checksum:
    has-duplicate-object-title:
    filename-valid:
      name: Filename validation
      description: Rule varies by collection. Some default pattern matches for meaningless file names
    unusual-file-size:
      name: Unusual file size
      description: Compare file size to expectations for an extension type.  Re-compute based on the corpus. Determine some standard deviation rule to flag items.
    has-sidecar-metadata:
      name: Object has sidecar metadata
    localid-invalid:
      name: Local id conforms to naming standards for collection
    erc-invalid:
      name: ERC metadata conforms to naming standards for collection
    filesize-invalid:
      name: File size is within typical size range for the collection
  x-tests-bitstream:
    extension-mime-match:
      name: File Extension matches mime type
      description: If format identification has over-ruled the extension, make note of that.
      skip: true
    pii-detected:
      name: PII detected
      description: BITSTREAM SCAN assumes we could plug in such a service
    virus-detected:
      name: Virus detected
      description: |
        Lower priority for a preservation repository
        BITSTREAM SCAN
    format-id-scan:
      name: Format Identification Issue
      description: BITSTREAM SCAN
    file-accessibility-scan:
      name: File Accessibility Issue
      description: BITSTREAM SCAN
