default:
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: "{!SSM: billing/db-host}"
    database: "{!SSM: billing/db-name}"
    port: 3306
    username: "{!SSM: billing/readwrite/db-user}"
    password: "{!SSM: billing/readwrite/db-password}"