default:
  dbconf:
    adapter: mysql2
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    host: "{!SSM: billing/db-host}"
    database: "{!SSM: billing/db-name}"
    port: 3306
    username: "{!SSM: billing/readwrite/db-user}"
    password: "{!SSM: billing/readwrite/db-password}"
  gather-ids:
    limit: 10
    select: |
      select o.id
      from inv.inv_objects o
      inner join inv.inv_collections_inv_objects icio on icio.inv_object_id = o.id
      inner join inv.inv_collections c on c.id = icio.inv_collection_id
      where 1=1
    exclusion: |
      and not exists (select 1 from object_health_json h where h.inv_object_id = o.id)
      order by o.modified desc
      limit ?
    # prioritized set of queries to use to find work to be performed.  If one query returns no results, the next one will be run
    queries:
    # find items with inv_metadatas in merritt_demo
    - |
      and c.mnemonic = 'merritt_demo'
      and exists (select 1 from inv.inv_metadatas where inv_object_id=o.id)
    # find items in merritt_demo
    - |
      and c.mnemonic = 'merritt_demo'
  analysis:
    mime:
      PASS:
      - text/plain
      - application/xml
      - image/jpeg
      - image/tiff
      - application/xhtml+xml
      - application/pdf
      - application/atom+xml
      - image/gif
      - text/csv
      - application/x-gzip
      - text/html
      - image/png
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - application/zip
      - application/msword
      - audio/x-wav
      - audio/mpeg
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - application/json
      - application/mxf
      - application/gzip
      - application/vnd.ms-excel
      - video/mp4
      - video/quicktime
      - application/vnd.openxmlformats-officedocument.presentationml.presentation
      - application/vnd.ms-powerpoint
      SKIP:
      - plain/turtle
      - application/rdf+xml
      FAIL:
      WARN:
      - application/octet-stream
      INFO:
      - application/x-hdf
      - application/x-matlab-data
      - text/x-rsrc
      - application/x-gtar
      - application/rtf
      - audio/x-aiff
      - application/postscript
      - text/x-actionscript
      - image/vnd.adobe.photoshop
      - audio/vnd.wave
      - application/x-tika-msoffice
      - application/x-rar-compressed
      - application/x-netcdf
      - video/x-msvideo
      - model/vnd.mts
      - text/tab-separated-values
      - image/x-raw-panasonic
      - text/x-matlab
      - application/x-dbf
      - application/x-7z-compressed
      - application/x-shapefile
      - text/x-vcard
      - video/x-matroska
      - application/x-tar
      - image/svg+xml
      - image/x-raw-canon
      - video/mpeg
      - application/xv+xml
      - video/x-ms-wmv
      - audio/x-ms-wma
      - application/x-shockwave-flash
      - text/x-python
      - video/x-m4v
      - application/x-sh
      - application/x-dosexec
      - multipart/appledouble
      - application/java-vm
      - image/x-ms-bmp
      - text/x-objcsrc
      - application/x-webarchive
      - application/x-bzip2
      - message/rfc822
      - application/vnd.ms-pki.stl
      - text/x-ruby
      - application/x-tika-ooxml
      - text/x-log
      - text/x-perl
      - application/marc
      - text/x-web-markdown
      - application/dicom
      - application/vnd.oasis.opendocument.spreadsheet
      - application/x-adobe-indesign
      - video/x-flv
      - audio/mp4
      - application/vnd.quark.quarkxpress
      - application/vnd.syncml.dm+wbxml
      - text/x-php
      - application/vnd.ms-excel.sheet.4
      - application/x-sqlite3
      - application/x-iso9660-image
      - image/bmp
      - application/javascript
      - application/vnd.oasis.opendocument.text
      - text/x-csrc
      - application/vnd.ms-outlook
      - application/x-pkcs7-certificates
      - text/x-c++src
      - application/vnd.google-earth.kmz
      - application/x-stata-dta; version=14
      - text/css
      - application/x-elc
      - application/x-tex
      - text/troff
      - text/x-java-source
      - application/x-font-ttf
      - application/java-archive
      - application/x-font-otf
      - image/x-pict
      - application/x-123
      - image/vnd.radiance
      - chemical/x-cif
      - application/vnd.ms-works
      - application/mathematica
      - application/vnd.ms-excel.sheet.binary.macroenabled.12
      - application/vnd.wordperfect
      - application/vnd.ms-excel.sheet.macroenabled.12
      - application/x-sas
      - application/x-bplist
      - application/zlib
      - application/x-xz
      - video/3gpp
      - application/illustrator
      - text/x-fortran
      - audio/vorbis
      - application/vnd.wordperfect; version=6.x
      - application/vnd.google-earth.kml+xml
      - audio/basic
      - text/x-chdr
      - application/x-msdownload; format=pe32
      - application/x-font-bdf
      - application/vnd.apple.pages
      - application/vnd.oasis.opendocument.base
      - video/x-ms-asf
      - text/x-sql
      - application/x-stuffit
      - application/vnd.apple.numbers
      - application/vnd.rn-realmedia
      - application/vnd.ms-word.document.macroenabled.12
      - application/x-msaccess
      - application/rss+xml
      - text/sgml
      - application/x-erdas-hfa
      - text/x-coldfusion
      - application/x-stata-dta
      - application/x-stata-dta; version=13
      - application/vnd.adobe.xfl
      - image/x-portable-bitmap
      - application/x-sas-audit
      - text/x-pascal
      - application/x-bzip
      - application/vnd.iccprofile
      - application/x-bat
      - text/x-rst
      - image/vnd.dxf; format=ascii
      - application/x-sas-data
      - application/epub+zip
      - image/vnd.zbrush.pcx
      - text/x-d
      - image/x-portable-graymap
      - application/vnd.mcd
      - image/x-xcf
      - audio/midi
      - application/x-mspublisher
      - image/vnd.microsoft.icon
      - application/x-bibtex-text-file
      - application/x-compress
      - application/x-mobipocket-ebook
      - application/vnd.visio
      - application/vnd.ms-xpsdocument
      - application/smil+xml
      - text/x-prolog
      - application/vnd.ms-spreadsheetml
      - message/news
      - application/vnd.apple.keynote
      - application/vnd.adobe.air-application-installer-package+zip
      - text/x-ml
      - application/vnd.adobe.indesign-idml-package
      - application/x-sharedlib
      - application/fits
      - text/vnd.graphviz
      - text/x-asciidoc
      - application/sereal; version=3
      - text/x-assembly
      - text/x-basic
      - text/x-yaml
      - application/msword2
      - application/vnd.ms-tnef
      - image/x-portable-pixmap
      - application/vnd.ms-word2006ml
      - text/x-vbasic
      - application/x-ms-owner
      - text/x-ini
      - application/vnd.yamaha.smaf-phrase
      - application/vnd.ms-excel.sheet.3
      - image/x-icon
      - text/x-diff
      - application/vnd.lotus-freelance
      - application/x-dtbresource+xml
      - application/x-msdownload
      - application/x-msdownload; format=pe64
      - text/x-tcl
      - message/x-emlx
      - application/msword5
      - text/x-common-lisp
      - application/vnd.ms-powerpoint.presentation.macroenabled.12
      - text/x-aspectj
      - application/vnd.oasis.opendocument.chart
      - application/x-executable
      - application/vnd.oasis.opendocument.presentation
      - application/x-pkcs12
      - text/x-modula
      - image/wmf
      - text/calendar
      - application/vnd.openxmlformats-officedocument.presentationml.template
      - application/x-xfig
      - chemical/x-cdx
      - application/vnd.openxmlformats-officedocument.spreadsheetml.template
      - application/vnd.chipnuts.karaoke-mmd
      - text/prs.lines.tag
      - application/pgp-signature
      - text/x-groovy
      - application/vnd.tcpdump.pcap
      - text/x-haml
      - application/vnd.mif
      - text/x-stsrc
      - application/x-emf
      - application/vnd.ms-cab-compressed
      - image/vnd.dwg
      - application/vnd.adobe.fxp
      - application/x-font-linux-psf
      - application/mbox
      - text/x-c++hdr      -       -       -       -       -       -       -      | software   |      - 1 |
  tests:
    aaa:
      name: Test AAA
    bbb:
      name: Test BB
    ccc:
      name: Test C
  x-tests:
    extension-mime-match:
      name: File Extension matches mime type
      description: If format identification has over-ruled the extension, make note of that.
      skip: true
    sustainable-mime:
      name: Mime type sustainability
      description: Compare file extention (or known mime type) to a list of sustainable mime types.
    filename-valid:
      name: Filename validation
      description: Rule varies by collection. Some default pattern matches for meaningless file names
    empty-file:
      name: Empty file detection
      description: Check file size
    unusual-file-size:
      name: Unusual file size
      description: Compare file size to expectations for an extension type.  Re-compute based on the corpus. Determine some standard deviation rule to flag items.
    file-claasified:
      name: Classify Files
      description: Classify file as content, metadata, other. Look at mime type, file size, file name.
    has-content-files:
      name: Object has content files
    has-sidecar-metadata:
      name: Object has sidecar metadata
    has-content-and-sidecar-metadata:
      name: Object has content + sidecar metadata
    has-meaningful=erc:
      name: Object has meaningful ERC metadata
    has-local-id:
      name: Object has local id
    has-embargo:
      name: Has embargo / had embargo
    has-duplicate-checksum:
      name: Has duplicate checksum
    localid-valid:
      name: Local id conforms to naming standards for collection
    erc-valid:
      name: ERC metadata conforms to naming standards for collection
    filesize-valid:
      name: File size is within typical size range for the collection
    pii-detected:
      name: PII detected
      description: BITSTREAM SCAN assumes we could plug in such a service
    virus-detected:
      name: Virus detected
      description: BITSTREAM SCAN
    format-id-scan:
      name: Format Identification Issue
      description: BITSTREAM SCAN