merritt: 
  credential: "{!SSM: objhealth/merritt_credential}"
  fits_command: "/home/tbrady/fits/fits.sh"
  fits_config: "/home/tbrady/fits/xml/fits_merritt.xml"
options:
  fmt: default
  page_size: 10
  start: 0
  limit: 10
  max_file_per_object: 1000
  output: console,
  max_file_size: 1000000000
outputs:
  console: 
    class: ConsoleOutput
  arks: 
    class: ArksOutput
  files: 
    class: FilesOutput
  fits: 
    class: FitsOutput
  fits-filtered: 
    class: FitsFilteredOutput

queries:
  default:
    class: OSFormatter
    # https://opensearch.org/docs/latest/query-dsl/term/exists/
    query:
      exists: 
        field: id
  files:
    class: OSFilesFormatter
    # https://opensearch.org/docs/latest/query-dsl/term/exists/
    query:
      exists: 
        field: id
  unsustainable:
    class: UnsustainableMimeFormatter
    # https://opensearch.org/docs/latest/query-dsl/full-text/match/
    # https://opensearch.org/docs/latest/query-dsl/compound/bool/
    query:
      bool:
        should:
        - match: 
            tests.results.unsustainable-mime-type: FAIL
        - match: 
            tests.results.unsustainable-mime-type: WARN
        - match: 
            tests.results.unsustainable-mime-type: INFO
  ext_mismatch:
    class: ExtensionMismatchFormatter
    query:
      match: 
        tests.results.mime-extension-mismatch: FAIL
  unclassified_mime:
    class: UnclassifiedMimeFormatter
    query:
      match: 
        tests.results.mime-not-found: FAIL
  # bundle exec ruby object_health_query.rb --fmt=octet-stream --file_mime_regex=octet-stream --output=fits --max_file_per_object=5
  octet-stream:
    class: OSFilesFormatter
    query:
      match: 
        build.producer.mime_type: octet-stream
